name: Lint
on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize]
jobs:
  lint:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - run: npm run lint
